---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./test/ui.tsx"
postMerge:
  pattern: 
    - "./test/ui.tsx"
postRun:
     command:
        - yarn --version
configFile: package.json
version: 1.0