---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./test/*{.ts,.tsx}"
postMerge:
  pattern: 
    - "./test/*{.ts,.tsx}"
postRun:
     command:
        - yarn --version
configFile: package.json
version: 1.0